In [6]:
import torch
import numpy as np

In [8]:
# Environment verification

print(f"Pytorch version: {torch.__version__}.")
print(f"CUDA availability: {torch.cuda.is_available()}.")
print(f"Number of devices: {torch.cuda.device_count()}.")
print(f"Current device index: {torch.cuda.current_device()}.")
print(f"Current device name: {torch.cuda.get_device_name(torch.cuda.current_device())}.")

Pytorch version: 2.13.0+cu130.
CUDA availability: True.
Number of devices: 1.
Current device index: 0.
Current device name: NVIDIA GeForce RTX 5060 Laptop GPU.


In [ ]:
# First tensor

data = [[17,70],[1,3]]
x_data = torch.tensor(data)

print(x_data)

np_array = np.array(data)
print(type(np_array))
x_np = torch.tensor(np_array)
print(x_data)
print(type(x_data))

tensor([[17, 70],
        [ 1,  3]])
<class 'numpy.ndarray'>
tensor([[17, 70],
        [ 1,  3]])
<class 'torch.Tensor'>


In [ ]:
"""
Initializing with another tensor
"""

# Inherit shapes and dtype from x_data
x_ones = torch.ones_like(x_data)
print(x_ones)

# Same with first but with zeros
x_zeros = torch.zeros_like(x_ones)
print(x_zeros)

# Create tensor with shape of x_data, but overriding dtype
x_rand_2 = torch.rand_like(x_data, dtype=torch.float)
print(x_rand_2)

tensor([[1, 1],
        [1, 1]])
tensor([[0, 0],
        [0, 0]])
tensor([[0.5960, 0.3756],
        [0.0922, 0.4633]])


In [ ]:
"""
    Initializing with random or constant value
"""

shape = (2,3)

# Create new tensor prefilled with ones, zeroes, and random
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
rand_tensor = torch.rand(shape)

print(ones_tensor)
print(zeros_tensor)
print(rand_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.4757, 0.2519, 0.2066],
        [0.3687, 0.1357, 0.6381]])


In [ ]:
"""
    Attributes of a tensor
"""

tensor = torch.rand(3,4)

print(f"Shape: {tensor.shape}")
print(f"Datatype: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape: torch.Size([3, 4])
Datatype: torch.float32
Device tensor is stored on: cpu


In [24]:
"""
    Tensor operations can be run on CPU and Accelerator (CUDA, MPS, MTIA, XPU).

    By default, tensors are created on CPU. Use the tensor.to() method to move tensor to Accelerator
    (After checking their availability).

    Keep in mind copying tensor across devices can be expensive in time and memory
"""

print(torch.accelerator.current_accelerator())

tensor = torch.rand(4,4)

if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

print(tensor)

cuda
tensor([[0.6508, 0.0922, 0.8149, 0.5731],
        [0.9620, 0.4465, 0.7288, 0.9331],
        [0.1716, 0.7949, 0.2199, 0.6555],
        [0.3887, 0.8718, 0.0455, 0.6828]], device='cuda:0')


In [23]:
"""
    Some slicing/indexing tensor operations

    These are very NumPy adjacent syntax
"""

tensor = torch.rand(4,4)

# Slicing and indexing
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:,0]}")
print(f"Last column: {tensor[:,-1]}")

# Concatenating tensor along a dimension
print(torch.cat([tensor,tensor],dim=1))
print(torch.cat([tensor,tensor],dim=0))

First row: tensor([0.6020, 0.3144, 0.0301, 0.7496])
First column: tensor([0.6020, 0.5465, 0.7294, 0.2430])
Last column: tensor([0.7496, 0.3772, 0.2375, 0.6145])
tensor([[0.6020, 0.3144, 0.0301, 0.7496, 0.6020, 0.3144, 0.0301, 0.7496],
        [0.5465, 0.0983, 0.9802, 0.3772, 0.5465, 0.0983, 0.9802, 0.3772],
        [0.7294, 0.1911, 0.3513, 0.2375, 0.7294, 0.1911, 0.3513, 0.2375],
        [0.2430, 0.2552, 0.3097, 0.6145, 0.2430, 0.2552, 0.3097, 0.6145]])
tensor([[0.6020, 0.3144, 0.0301, 0.7496],
        [0.5465, 0.0983, 0.9802, 0.3772],
        [0.7294, 0.1911, 0.3513, 0.2375],
        [0.2430, 0.2552, 0.3097, 0.6145],
        [0.6020, 0.3144, 0.0301, 0.7496],
        [0.5465, 0.0983, 0.9802, 0.3772],
        [0.7294, 0.1911, 0.3513, 0.2375],
        [0.2430, 0.2552, 0.3097, 0.6145]])


In [ ]:
"""
    Matrix multiplication
"""

tensor = torch.rand(3,4)

print(f"OG tensor:\n {tensor}")

# All of these describes standard matrix multiplication
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.empty(0)
torch.matmul(tensor, tensor.T, out=y3)

print(y1)
print(y2)
print(y3)


OG tensor:
 tensor([[0.4974, 0.5094, 0.3427, 0.9496],
        [0.7070, 0.6885, 0.2148, 0.8890],
        [0.8923, 0.4454, 0.2245, 0.0223]])
tensor([[1.5261, 1.6201, 0.7688],
        [1.6201, 1.8102, 1.0055],
        [0.7688, 1.0055, 1.0454]])
tensor([[1.5261, 1.6201, 0.7688],
        [1.6201, 1.8102, 1.0055],
        [0.7688, 1.0055, 1.0454]])
tensor([[1.5261, 1.6201, 0.7688],
        [1.6201, 1.8102, 1.0055],
        [0.7688, 1.0055, 1.0454]])


In [ ]:
"""
    Element-wise product
"""

tensor = torch.rand(3,4)
print(f"OG tensor:\n{tensor}")

# Again, all three methods achieve the same element-wise multiplication
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.empty(0)
z3 = torch.mul(tensor,tensor,out=z3)
print(z1)
print(z2)
print(z3)

OG tensor:
tensor([[0.7567, 0.8124, 0.9117, 0.6000],
        [0.0197, 0.0752, 0.2681, 0.3673],
        [0.9593, 0.0449, 0.2783, 0.9067]])
tensor([[5.7252e-01, 6.5994e-01, 8.3116e-01, 3.6005e-01],
        [3.8986e-04, 5.6563e-03, 7.1867e-02, 1.3487e-01],
        [9.2026e-01, 2.0122e-03, 7.7456e-02, 8.2202e-01]])
tensor([[5.7252e-01, 6.5994e-01, 8.3116e-01, 3.6005e-01],
        [3.8986e-04, 5.6563e-03, 7.1867e-02, 1.3487e-01],
        [9.2026e-01, 2.0122e-03, 7.7456e-02, 8.2202e-01]])
tensor([[5.7252e-01, 6.5994e-01, 8.3116e-01, 3.6005e-01],
        [3.8986e-04, 5.6563e-03, 7.1867e-02, 1.3487e-01],
        [9.2026e-01, 2.0122e-03, 7.7456e-02, 8.2202e-01]])


# Tensors

Mathematically, tensor is a generalization of a scalar, vector, or a matrix. They are characterized by their order, which specify the number of dimension a tensor can have. A scalar is a tensor with order 0, vector is a tensor with order 1, matrix is a tensor with order 2, etc. In a computational sense, we can think of tensors as a multi-dimensional array.

In PyTorch, tensor is implemented as an efficient data container supporting a multitude of operations. It is somewhat similar to a numpy array, though it supports more features useful to deep learning (differentiation, etc), and can run on a GPU.